{
  config,
  pkgs,
  lib,
  ...
}: let
  inherit (lib) mkIf;
  cfg = config.cli;
  primaryUsername = config.primaryUser.name;

  mc_catppuccin = pkgs.fetchFromGitHub {
    owner = "catppuccin";
    repo = "mc";
    rev = "23562615818820900c8967fb3fe2779182763f12";
    hash = "sha256-3qnbAt1AjyCNfoBT6vVGmAwNGYS2zOh81GRA7/shbVA=";
  };

  # Every helper under libexec/mc/ext.d shells out to bare command names
  # (`file`, `pdftotext`, `unzip`, ...). Rather than dumping all of them into
  # the system PATH, mc itself is wrapped with them so its handlers always
  # resolve; children inherit the wrapper's PATH.
  mcHelpers = with pkgs; [
    file # ext.d/* all start by running `file` on the target
    p7zip # 7z / 7za (archive.sh, misc.sh); cli.nix only ships 7zz
    unrar
    unzip
    zip
    cabextract
    zstd
    lz4
    lzop
    brotli
    squashfsTools
    cdrkit # isoinfo, for ISO9660 viewing
    poppler-utils # pdftotext
    catdoc # catdoc, xls2csv
    odt2txt
    w3m # web.sh html rendering
    exiftool # image.sh
    mediainfo # sound.sh / video.sh
    sqlite.bin
    groff # nroff, for man/troff pages
  ];

  mcPackage = pkgs.symlinkJoin {
    name = "mc-${pkgs.mc.version}-wrapped";
    paths = [pkgs.mc];
    nativeBuildInputs = [pkgs.makeWrapper];
    postBuild = ''
      for bin in mc mcedit mcview mcdiff; do
        [ -e "$out/bin/$bin" ] || continue
        wrapProgram "$out/bin/$bin" \
          --suffix PATH : ${lib.makeBinPath mcHelpers}
      done
    '';
  };

  extD = "${pkgs.mc}/libexec/mc/ext.d";

  openCmd =
    if pkgs.stdenv.isDarwin
    then "open %d/%p"
    else "${lib.getExe' pkgs.util-linux "setsid"} -f ${lib.getExe' pkgs.xdg-utils "xdg-open"} %d/%p";

  # mc reads mc.ext.ini with GKeyFile, which unescapes a value before handing
  # it to the regex engine, so a literal backslash has to be doubled on disk.
  # Nix strings below hold the plain pattern; this puts the file escaping back.
  escapeIniValue = lib.replaceStrings ["\\"] ["\\\\"];
  toExtIni = groups:
    lib.generators.toINI {} (lib.mapAttrs (_: lib.mapAttrs (_: escapeIniValue)) groups);

  # Rules layered on top of mc's own mc.ext.ini. They are emitted *before* the
  # stock rules because mc walks groups in file order and stops at the first
  # match. Group names must not collide with a stock one — GKeyFile folds
  # duplicate groups together and the later (stock) keys would win.
  extraExtGroups = {
    apk = {
      Type = "Android package \\(APK\\)";
      TypeIgnoreCase = "true";
      Open = "%cd %p/uzip://";
      View = "%view{ascii} ${extD}/archive.sh view zip";
    };
    squashfs = {
      Type = "^Squashfs filesystem";
      # No usqfs:// VFS ships with mc, so there is no Open here; listing the
      # image is the most that can be done without an external extfs handler.
      View = "%view{ascii} ${lib.getExe' pkgs.squashfsTools "unsquashfs"} -stat %f ; ${lib.getExe' pkgs.squashfsTools "unsquashfs"} -lls -d \"\" %f";
    };
    brotli = {
      Shell = ".br";
      ShellIgnoreCase = "true";
      # ext.d/archive.sh has no brotli case and there is no brotli:// VFS, so
      # drive the decompressor directly, the way stock does for gzip.
      Open = "${lib.getExe pkgs.brotli} -dc %f | %var{PAGER:more}";
      View = "%view{ascii} ${lib.getExe pkgs.brotli} -dc %f";
    };
    heic = {
      Shell = ".heic";
      ShellIgnoreCase = "true";
      Include = "image";
    };
    heif = {
      Shell = ".heif";
      ShellIgnoreCase = "true";
      Include = "image";
    };
    hif = {
      Shell = ".hif";
      ShellIgnoreCase = "true";
      Include = "image";
    };
  };

  # [Default] is resolved by name rather than by position, so it can sit last.
  defaultExtGroup.Default = {
    Open = openCmd;
    View = openCmd;
  };

  mcExtIni =
    pkgs.runCommandLocal "mc.ext.ini" {
      extra = toExtIni extraExtGroups;
      fallback = toExtIni defaultExtGroup;
      passAsFile = ["extra" "fallback"];
    } ''
      {
        echo '# Generated by nixos-config modules/apps/mc — do not edit.'
        echo
        cat "$extraPath"
        # Stock rules verbatim, so they track the mc package on every bump. The
        # stock [Default] group is empty and terminates the file; drop it so the
        # xdg-open fallback below is the only one.
        sed '/^\[Default\]/,$d' ${pkgs.mc}/etc/mc/mc.ext.ini
        cat "$fallbackPath"
      } > $out
    '';

  mcHomeConfig = {
    xdg.dataFile."mc/skins/catppuccin.ini".source = "${mc_catppuccin}/catppuccin.ini";

    # mc replaces its extension file wholesale rather than merging, and
    # home-manager's extensionSettings renders through `toINI` which sorts
    # groups alphabetically. mc needs the stock order (filename rules before
    # `file`-magic rules), so the file is assembled directly instead.
    xdg.configFile."mc/mc.ext.ini".source = mcExtIni;

    programs.mc = {
      enable = true;
      package = mcPackage;
      settings = {
        Midnight-Commander = {
          verbose = true;
          shell_patterns = true;
          auto_save_setup = false;
          preallocate_space = false;
          auto_menu = false;
          use_internal_view = true;
          use_internal_edit = false;
          clear_before_exec = true;
          confirm_delete = true;
          confirm_overwrite = true;
          confirm_execute = false;
          confirm_history_cleanup = true;
          confirm_exit = false;
          confirm_directory_hotlist_delete = false;
          confirm_view_dir = false;
          safe_delete = false;
          safe_overwrite = false;
          use_8th_bit_as_meta = false;
          mouse_move_pages_viewer = true;
          mouse_close_dialog = false;
          fast_refresh = false;
          drop_menus = false;
          wrap_mode = true;
          old_esc_mode = true;
          cd_symlinks = false;
          show_all_if_ambiguous = false;
          use_file_to_guess_type = true;
          alternate_plus_minus = false;
          only_leading_plus_minus = true;
          show_output_starts_shell = false;
          xtree_mode = false;
          file_op_compute_totals = true;
          classic_progressbar = true;
          use_netrc = false;
          ftpfs_always_use_proxy = false;
          ftpfs_use_passive_connections = true;
          ftpfs_use_passive_connections_over_proxy = false;
          ftpfs_use_unix_list_options = true;
          ftpfs_first_cd_then_ls = true;
          ignore_ftp_chattr_errors = true;
          editor_backspace_through_tabs = false;
          editor_option_save_position = true;
          editor_option_auto_para_formatting = false;
          editor_option_typewriter_wrap = false;
          editor_edit_confirm_save = true;
          editor_syntax_highlighting = true;
          editor_persistent_selections = true;
          editor_drop_selection_on_copy = true;
          editor_cursor_beyond_eol = false;
          editor_cursor_after_inserted_block = false;
          editor_visible_tabs = true;
          editor_visible_spaces = true;
          editor_line_state = false;
          editor_simple_statusbar = false;
          editor_check_new_line = false;
          editor_show_right_margin = false;
          editor_group_undo = false;
          editor_state_full_filename = false;
          editor_ask_filename_before_edit = false;
          nice_rotating_dash = true;
          shadows = true;
          mcview_remember_file_position = false;
          auto_fill_mkdir_name = true;
          copymove_persistent_attr = true;
          pause_after_run = 2;
          mouse_repeat_rate = 100;
          double_click_speed = 250;
          old_esc_mode_timeout = 1000000;
          max_dirt_limit = 10;
          num_history_items_recorded = 60;
          vfs_timeout = 60;
          ftpfs_directory_timeout = 900;
          ftpfs_retry_seconds = 30;
          shell_directory_timeout = 900;
          editor_tab_spacing = 2;
          editor_fill_tabs_with_spaces = true;
          editor_return_does_auto_indent = true;
          editor_fake_half_tabs = false;
          editor_word_wrap_line_length = 100;
          editor_option_save_mode = 0;
          editor_backup_extension = "~";
          editor_filesize_threshold = "64M";
          editor_stop_format_chars = "-+*\\,.;:&>";
          skin = "catppuccin";
        };
        Layout = {
          output_lines = 0;
          top_panel_size = 0;
          message_visible = true;
          keybar_visible = true;
          xterm_title = true;
          command_prompt = true;
          menubar_visible = true;
          free_space = true;
          horizontal_split = false;
          vertical_equal = true;
          horizontal_equal = true;
        };
        Misc = {
          timeformat_recent = "%b %d %H:%M";
          timeformat_old = "%b %d  %Y";
          ftp_proxy_host = "gate";
          ftpfs_password = "anonymous@";
          display_codepage = "UTF-8";
          # Left off deliberately: any non-empty value other than "off" turns
          # enca autodetection on and feeds it this string as the language.
          autodetect_codeset = "off";
          clipboard_store =
            if config.graphical.enable
            then "${pkgs.wl-clipboard}/bin/wl-copy"
            else null;
          clipboard_paste =
            if config.graphical.enable
            then "${pkgs.wl-clipboard}/bin/wl-paste"
            else null;
        };
        Panels = {
          show_mini_info = true;
          kilobyte_si = false;
          mix_all_files = false;
          show_backups = true;
          show_dot_files = true;
          fast_reload = false;
          fast_reload_msg_shown = false;
          mark_moves_down = true;
          reverse_files_only = false;
          auto_save_setup_panels = false;
          navigate_with_arrows = false;
          panel_scroll_pages = true;
          panel_scroll_center = false;
          mouse_move_pages = true;
          filetype_mode = true;
          permission_mode = false;
          torben_fj_mode = false;
          quick_search_mode = 2;
          select_flags = 2;
        };
      };
      # Merged over mc's built-in keymap, so only the listed actions change.
      # ctrl-shift-r is indistinguishable from ctrl-r at the terminal, so the
      # default has to stay listed or panel reread becomes unreachable.
      keymapSettings.panel.Reread = "ctrl-r;ctrl-shift-r";
    };
  };
in {
  config = mkIf cfg.enable {
    environment.systemPackages = with pkgs;
      [
        file # also useful outside mc, and nothing else in the tree ships it
        p7zip
        unrar
        unzip
        zip
        mediainfo
      ]
      ++ lib.optionals config.graphical.enable [
        wl-clipboard
      ];
    home-manager.users.${primaryUsername} = mcHomeConfig;
    home-manager.users.root = mcHomeConfig;
  };
}
