# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    loader = {
      systemd-boot.enable = true;
      efi.canTouchEfiVariables = true;
      timeout = 1;
    };
    initrd = {
      systemd.enable = true;
      availableKernelModules = [
        "nvme"
        "xhci_pci"
        "ahci"
        "usbhid"
        "usb_storage"
        "sd_mod"
        "sr_mod"
        "hid_generic"
      ];
      kernelModules = [];
      luks.devices."luks-4110bc56-975a-4d51-b39e-9452ea0294f7".device = "/dev/disk/by-uuid/4110bc56-975a-4d51-b39e-9452ea0294f7";
    };
    kernelModules = [
      "kvm-amd"
      "k10temp"
      "it87"
      "amdgpu"
    ];
    extraModulePackages = [
      config.boot.kernelPackages.r8125
      config.boot.kernelPackages.it87
    ];
    blacklistedKernelModules = [
      "gigabyte-wmi"
    ];
    kernelParams = [
      "systemd.show_status=true"
      "rd.udev.log_level=3"
      "preempt=full"
      "amd_pstate=active" # AMD Active Pstates instead of cpufreq
      "tsc=reliable" # Trust AMD builtin clock for better latency
      "clocksource=tsc" # Trust AMD builtin clock for better latency
      "iommu=pt"
      "thermal.crt=105" # Fix a bug with acpitz reporting overheat on resume from suspend
      "plymouth.use-simpledrm"
      "acpi_enforce_resource=lax"
      "amdgpu.aspm=0" # Disable PCIe ASPM to prevent SMU firmware deadlock on Navi22 during runtime
      "amdgpu.runpm=0" # Keep GPU in D0 during runtime idle; prevents entering D3 between frames
      "no_console_suspend" # TEMPORARY: keep console alive during suspend to diagnose second-sleep hang
      "panic=300" # TEMPORARY: wait 5 min before reboot on panic so we can read the backtrace
    ];
    extraModprobeConfig = ''
      options it87 ignore_resource_conflict=1
      # Disable ALSA power management to prevent audio device suspension
      # This fixes audio delay and white noise issues when devices wake from suspend
      options snd_hda_intel power_save=0 power_save_controller=N
      options snd_ac97_codec power_save=0
    '';
    kernel.sysctl = {
      "vm.swappiness" = 10;
      "vm.max_map_count" = 524288; # 64GB ram,
      "vm.vfs_cache_pressure" = 50; # more memory for filesystem data
      "vm.dirty_ratio" = 30;
      "vm.dirty_background_ratio" = 15;
      "net.core.default_qdisc" = "fq";
      "net.ipv4.tcp_congestion_control" = "bbr";
    };
    # Navi22 (RX 6700 XT): RunDcBtc SMU calibration times out on every resume.
    # sienna_cichlid_run_btc() propagates -ETIMEDOUT which wedges amdgpu resume.
    # sed matches by text content so this survives kernel micro-version bumps.
    kernelPackages = pkgs.linuxPackagesFor (pkgs.linuxPackages_latest.kernel.overrideAttrs (old: {
      postPatch =
        (old.postPatch or "")
        + ''
          if [ -f drivers/gpu/drm/amd/pm/swsmu/smu11/sienna_cichlid_ppt.c ]; then
            sed -i 's/"RunDcBtc failed!\\n"/"RunDcBtc failed, ignoring\\n"/' \
              drivers/gpu/drm/amd/pm/swsmu/smu11/sienna_cichlid_ppt.c
            sed -i '/static int sienna_cichlid_run_btc/,/^}/{s/\treturn res;/\treturn 0;/}' \
              drivers/gpu/drm/amd/pm/swsmu/smu11/sienna_cichlid_ppt.c
          fi
        '';
    }));
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/789d3481-8d64-4a39-b219-95b98db2a3a7";
    fsType = "ext4";
    options = [
      "noatime"
      "nodiratime"
      "x-systemd.device-timeout=infinity"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/0C4B-B2B3";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    {
      device = "/swapfile";
      size = 64 * 1024; # 64GB
    }
  ];

  environment.etc = {
    "sysconfig/lm_sensors".text = ''
      HWMON_MODULES="it87"
    '';
    "sensors.d/gigabyte-x570.conf".text = ''
      chip "it8688-*"
        label fan1 "CPU_FAN"
        label fan2 "SYS_FAN1"
        label fan3 "SYS_FAN2"
        label fan4 "Chipset fan"
        label fan5 "CPU_OPT"

        label temp1 "SYS1 (rear)"
        label temp2 "SYS2 (front)"
        label temp3 "CPU"
        label temp4 "PCIe"
        label temp5 "VRM"
        label temp6 "Chipset"

      chip "it8688-*"
        label in0 "Vcore"

        label in1 "+3.3V"
        compute in1 1.65*@,@/1.65

        label in2 "+12V"
        compute in2  @ * (72/12), @ / (72/12)

        label in3 "+5V"
        compute in3 2.5*@,@/2.5

        label in4 "SoC"

        label in5 "VDDP"

        label in6 "DRAM A/B"
        compute in6 @-.03,@-.03
    '';
  };

  networking.modemmanager.enable = false;

  hardware = {
    bluetooth = {
      enable = true;
      powerOnBoot = true;
    };
    enableRedistributableFirmware = true;
    block.defaultScheduler = "none";
    keyboard.qmk.enable = true;
    flipperzero.enable = true;
    cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  };

  services = {
    udev.extraRules = ''
      KERNEL=="hidraw*", SUBSYSTEM=="hidraw", ATTRS{idVendor}=="3434", MODE="0660", GROUP="users", TAG+="uaccess"
    '';
    #  thermald.enable = true;
    hardware.bolt.enable = true;
    irqbalance.enable = true;
    fwupd.enable = true;
    fstrim.enable = true;
    pulseaudio.enable = false;
    pipewire = {
      enable = true;
      alsa = {
        enable = true;
        support32Bit = true;
      };
      pulse.enable = true;
      # Configure sample rates to match your DAC's capabilities
      extraConfig.pipewire."92-low-latency" = {
        context.properties = {
          default.clock = {
            allowed-rates = [
              44100
              48000
              88200
              96000
              176400
              192000
            ];
            rate = 48000;
            quantum = 256; # Lower from 1024 for less delay
            min-quantum = 32;
            max-quantum = 2048;
          };
          # Prevent device suspension
          node.pause-on-idle = false;
          session.suspend-timeout-seconds = 0;
        };
        context.modules = [
          {
            name = "libpipewire-module-rt";
            args = {
              nice.level = -11;
              rt = {
                prio = 88;
                time = {
                  soft = 2000000;
                  hard = 2000000;
                };
              };
            };
            flags = [
              "ifexists"
              "nofail"
            ];
          }
          {
            name = "libpipewire-module-protocol-pulse";
            args = {
              server.address = ["unix:native"];
            };
          }
        ];
      };
      # Set highest quality resampling when needed
      extraConfig.pipewire-pulse."92-low-latency" = {
        pulse.properties = {
          pulse = {
            min = {
              req = "256/48000";
              quantum = "64/48000";
            };
            default.req = "64/48000";
            max = {
              req = "128/48000";
              quantum = "128/48000";
            };
          };
        };
        stream.properties = {
          resample.quality = 5;
        };
      };
      # Enhanced WirePlumber configuration to prevent audio suspension
      # This fixes: 1) Delay when starting playback, 2) White noise on device wake
      wireplumber.extraConfig = {
        # Configure the AMD motherboard audio device
        "51-starship-matisse-profile" = {
          "monitor.alsa.rules" = [
            {
              matches = [
                {"device.product.name" = "Starship/Matisse HD Audio Controller";}
              ];
              actions = {
                update-props = {
                  "device.profile" = "iec958-stereo";
                  "session.suspend-timeout-seconds" = 0;
                  "api.alsa.period-size" = 256;
                  "api.alsa.headroom" = 1024;
                };
              };
            }
          ];
        };

        # Prevent ALL audio nodes from suspending (applies to all devices)
        "52-prevent-node-suspension" = {
          "monitor.alsa.rules" = [
            {
              matches = [
                {"node.name" = "~alsa_output.*";}
              ];
              actions = {
                update-props = {
                  "node.pause-on-idle" = false;
                  "session.suspend-timeout-seconds" = 0;
                  "api.alsa.period-size" = 256;
                  "api.alsa.headroom" = 1024;
                };
              };
            }
          ];
        };

        # Keep audio streams active
        "53-disable-stream-suspension" = {
          "wireplumber.settings" = {
            "node.features.audio.no-dsp" = false;
          };
          "monitor.alsa.rules" = [
            {
              matches = [
                {"media.class" = "Audio/Sink";}
              ];
              actions = {
                update-props = {
                  "node.pause-on-idle" = false;
                  "session.suspend-timeout-seconds" = 0;
                };
              };
            }
          ];
        };

        # Blue Yeti microphone - force 48kHz to avoid sample rate mismatch warnings
        "54-blue-yeti-sample-rate" = {
          "monitor.alsa.rules" = [
            {
              matches = [
                {"device.product.name" = "Yeti Stereo Microphone";}
              ];
              actions = {
                update-props = {
                  "audio.rate" = 48000;
                  "audio.allowed-rates" = "48000";
                };
              };
            }
          ];
        };
      };
    };
  };

  systemd = {
    tpm2.enable = true;
    # Grant irqbalance permission to set IRQ affinity (blocked by kernel hardening)
    services.irqbalance.serviceConfig.AmbientCapabilities = ["CAP_SYS_NICE"];
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  amd_gpu.enable = true;
  eizo = {
    enable = true;
    iccProfile = ../../modules/hardware/eizo/eizo-cg277.icc;
  };
}
