name: "Nix Check & Lint"
on:
  push:
    paths:
      - '**/*.nix'
  pull_request:
    paths:
      - '**/*.nix'
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Check Formatting (Alejandra)
        run: nix run nixpkgs#alejandra -- --check .
      - name: Linting (Statix)
        run: nix run nixpkgs#statix -- check .
      - name: Check for dead code (Deadnix)
        run: nix run nixpkgs#deadnix -- --fail .
      - name: Flake Check
        run: nix flake check
